### ISSUE TITLE
领域模型图里面QuestionnaireAnswer的问题

### ISSUE THREAD

**Issue by Chenxr1997** [code-flows-in-you/Dashboard#2]
一个问卷Questionnaire关联n个问题Question（1:n）  
一个问题Question关联n个选项Option（1:n）  
一个用户User关联n个答卷QuestionnaireAnswer（1:n）  
上面没有问题  
不过一个问卷Questionnaire也应该关联n个答卷QuestionnaireAnswer（1:n）  
一个答卷QuestionnaireAnswer关联n个Answer回答（1:n）  
1个回答Answer关联1个问题Question，1个问题Question关联n个回答Answer  
1个回答Answer关联n个选项Option（代表选择了这个选项），1个选项Option也应该关联n个回答Answer（n：m）

**Comment by lijm48** [comment]
已修改
