### ISSUE TITLE
数据库设计里面里面Problem，QAnswer和Best的问题

### ISSUE THREAD

**Issue by Chenxr1997** [code-flows-in-you/Dashboard#3]
对于一个回答QAnswer，他必须关联且关联一个问题Problem，因此QAnswer对应的match关系的线应该为粗线且打上箭头
对于Best，我感觉这个设置比较别扭，可以将它作为is_best属性加在match关系中，不过由于ER图的表达能力限制，不能表达出”对于一个问题Problem只有零个或一个对应的match的is_bset为true“这样的逻辑
在数据库的逻辑设计中，就可以把best作为问题Problem的一个属性，是一个qid(ER图不这样做的原因是它不符合ER图的设计理念)

**Comment by lijm48** [comment]
已部分修改
